### ISSUE TITLE
iOS 10 Swift 3 support

### ISSUE THREAD

**Issue by Toolenaar** [Azure/azure-notificationhubs-ios#16]
I have a project which I have just updated to swift 3 and iOS 10. I use the Windows.AzureMessaging.Framework in this project, but it seems the tutorial site (https://azure.microsoft.com/en-us/documentation/articles/notification-hubs-ios-apple-push-notification-apns-get-started/) does not point to an updated version for swift 3. Is there an updated version and if so where can I find it ?

**Comment by elvirberisha** [comment]
I found a solution and I post here all the steps to integrate the Azure Notification Hub with Swift:
1) On your project root, create a new Folder called "Headers"
2) Inside that Folder create a New File > Header File > Call it "HubInfo.h"
3) Copy this code inside your HubInfo.h file (remember to replace the values of HUBNAME and HUBLISTENACCESS with your project's hubName and hubConnString):
`
#ifndef HubInfo_h
#define HubInfo_h

#import <WindowsAzureMessaging/WindowsAzureMessaging.h>

#define HUBNAME @"<Enter the name of your hub>"
#define HUBLISTENACCESS @"<Enter your connection string>"

#endif /* HubInfo_h */
`
4) Select your project under "Targets" and then go to "Build Settings"
5) Search for "bridging header" in the search field
6) In "Objective-C Bridging Header" add your Header File: Headers/HubInfo.h
7) In your AppDelegate add "import UserNotifications" on the top
Then build the project and follow the tutorial here (starting from the step 8) using Swift instead of Objective-C: https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-ios-apple-push-notification-apns-get-started#connect-your-ios-app-to-notification-hubs

![Bridging-Header](https://user-images.githubusercontent.com/48671756/54980968-7ace8b80-4fa7-11e9-9efe-6c73700a28c8.png)

**Comment by marstr** [comment]
Seems like @elvirberisha has found a solution. I'm going to close/lock this issue as resolved.
